version: '3'
services:
  node0:
    image: ssh-server:ubuntu-22.04
    build:
      context: .
      dockerfile: Dockerfile
    hostname: node0
    volumes:
      - ../build:/build
  node1:
    image: ssh-server:ubuntu-22.04
    build:
      context: .
      dockerfile: Dockerfile
    hostname: node1
    volumes:
      - .:/build
  node2:
    image: ssh-server:ubuntu-22.04
    build:
      context: .
      dockerfile: Dockerfile
    hostname: node2
    volumes:
      - .:/build
  node3:
    image: ssh-server:ubuntu-22.04
    build:
      context: .
      dockerfile: Dockerfile
    hostname: node3
    volumes:
      - .:/build
  node4:
    image: ssh-server:ubuntu-22.04
    build:
      context: .
      dockerfile: Dockerfile
    hostname: node4
    volumes:
      - .:/build
